// export const SET_AUTH_USER = "SET_AUTH_USER";

export const SESSION = {
  AUTH: {
    LOGIN: {
      START: 'SESSION_AUTH_LOGIN_START',
      SUCCESS: 'SESSION_AUTH_LOGIN_SUCCESS',
      FAILURE: 'SESSION_AUTH_LOGIN_FAILURE'
    },
    LOGOUT: 'SESSION_AUTH_LOGOUT'
    // REGISTER: {
    //   START: 'SESSION_AUTH_REGISTER_START',
    //   SUCCESS: 'SESSION_AUTH_REGISTER_SUCCESS',
    //   FAILURE: 'SESSION_AUTH_REGISTER_FAILURE'
    // }
  }
};

// export const USER = {
//   REGISTER: {
//     START: 'USER_REGISTER_START',
//     SUCCESS: 'USER_REGISTER_SUCCESS',
//     FAILURE: 'USER_REGISTER_FAILURE'
//   },
//   PASSWORD_RESET: 'PASSWORD_RESET',
//   PASSWORD_UPDATE: 'PASSWORD_UPDATE'
// };
