export const AUTH = {
  LOGIN: {
    PENDING: 'AUTH_LOGIN_PENDING',
    SUCCESS: 'AUTH_LOGIN_SUCCESS',
    FAILURE: 'AUTH_LOGIN_FAILURE'
  },
  LOGOUT: 'AUTH_LOGOUT'
};

export const TWEET = {
  POST: {
    PENDING: 'TWEET_POST_PENDING',
    SUCCESS: 'TWEET_POST_SUCCESS',
    FAILURE: 'TWEET_POST_FAILURE'
  }
};
